apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-sample-deployment
  labels:
    app: flask-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-sample
  template:
    metadata:
      labels:
        app: flask-sample
    spec:
      containers:
      - name: flask-sample
        image: lorantonodi/flask-sample:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_PORT_27017_TCP_ADDR
          value: ""

---

apiVersion: v1
kind: Service
metadata:
  name: flask-sample-service
  labels:
    name: flask-sample-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: flask-sample